services:
  postgres:
    image: postgres:15-alpine
    container_name: lightcar_postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lightcar
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lightcar_backend
    restart: always
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/lightcar
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command:
      [
        'sh',
        '-c',
        'npm install && npx prisma migrate deploy && npx prisma db seed && npm run dev'
      ]

  frontend:
    build: ./frontend
    container_name: lightcar_frontend
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: ['sh', '-c', 'npm install && npm run dev']
# volumes:
#   postgres_data:
